/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sparqles.avro.analytics;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class IndexViewPerformance extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8447908175316675294L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"IndexViewPerformance\",\"namespace\":\"sparqles.avro.analytics\",\"fields\":[{\"name\":\"threshold\",\"type\":\"long\"},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndexViewPerformanceData\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"},{\"name\":\"color\",\"type\":\"string\"},{\"name\":\"data\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"IndexViewPerformanceDataValues\",\"fields\":[{\"name\":\"label\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"double\"}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<IndexViewPerformance> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<IndexViewPerformance> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<IndexViewPerformance> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<IndexViewPerformance> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<IndexViewPerformance> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this IndexViewPerformance to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a IndexViewPerformance from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a IndexViewPerformance instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static IndexViewPerformance fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long threshold;
  private java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public IndexViewPerformance() {}

  /**
   * All-args constructor.
   * @param threshold The new value for threshold
   * @param data The new value for data
   */
  public IndexViewPerformance(java.lang.Long threshold, java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> data) {
    this.threshold = threshold;
    this.data = data;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return threshold;
    case 1: return data;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: threshold = (java.lang.Long)value$; break;
    case 1: data = (java.util.List<sparqles.avro.analytics.IndexViewPerformanceData>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'threshold' field.
   * @return The value of the 'threshold' field.
   */
  public long getThreshold() {
    return threshold;
  }


  /**
   * Sets the value of the 'threshold' field.
   * @param value the value to set.
   */
  public void setThreshold(long value) {
    this.threshold = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> value) {
    this.data = value;
  }

  /**
   * Creates a new IndexViewPerformance RecordBuilder.
   * @return A new IndexViewPerformance RecordBuilder
   */
  public static sparqles.avro.analytics.IndexViewPerformance.Builder newBuilder() {
    return new sparqles.avro.analytics.IndexViewPerformance.Builder();
  }

  /**
   * Creates a new IndexViewPerformance RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new IndexViewPerformance RecordBuilder
   */
  public static sparqles.avro.analytics.IndexViewPerformance.Builder newBuilder(sparqles.avro.analytics.IndexViewPerformance.Builder other) {
    if (other == null) {
      return new sparqles.avro.analytics.IndexViewPerformance.Builder();
    } else {
      return new sparqles.avro.analytics.IndexViewPerformance.Builder(other);
    }
  }

  /**
   * Creates a new IndexViewPerformance RecordBuilder by copying an existing IndexViewPerformance instance.
   * @param other The existing instance to copy.
   * @return A new IndexViewPerformance RecordBuilder
   */
  public static sparqles.avro.analytics.IndexViewPerformance.Builder newBuilder(sparqles.avro.analytics.IndexViewPerformance other) {
    if (other == null) {
      return new sparqles.avro.analytics.IndexViewPerformance.Builder();
    } else {
      return new sparqles.avro.analytics.IndexViewPerformance.Builder(other);
    }
  }

  /**
   * RecordBuilder for IndexViewPerformance instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<IndexViewPerformance>
    implements org.apache.avro.data.RecordBuilder<IndexViewPerformance> {

    private long threshold;
    private java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(sparqles.avro.analytics.IndexViewPerformance.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.threshold)) {
        this.threshold = data().deepCopy(fields()[0].schema(), other.threshold);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.data)) {
        this.data = data().deepCopy(fields()[1].schema(), other.data);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing IndexViewPerformance instance
     * @param other The existing instance to copy.
     */
    private Builder(sparqles.avro.analytics.IndexViewPerformance other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.threshold)) {
        this.threshold = data().deepCopy(fields()[0].schema(), other.threshold);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.data)) {
        this.data = data().deepCopy(fields()[1].schema(), other.data);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'threshold' field.
      * @return The value.
      */
    public long getThreshold() {
      return threshold;
    }


    /**
      * Sets the value of the 'threshold' field.
      * @param value The value of 'threshold'.
      * @return This builder.
      */
    public sparqles.avro.analytics.IndexViewPerformance.Builder setThreshold(long value) {
      validate(fields()[0], value);
      this.threshold = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'threshold' field has been set.
      * @return True if the 'threshold' field has been set, false otherwise.
      */
    public boolean hasThreshold() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'threshold' field.
      * @return This builder.
      */
    public sparqles.avro.analytics.IndexViewPerformance.Builder clearThreshold() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public sparqles.avro.analytics.IndexViewPerformance.Builder setData(java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> value) {
      validate(fields()[1], value);
      this.data = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public sparqles.avro.analytics.IndexViewPerformance.Builder clearData() {
      data = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IndexViewPerformance build() {
      try {
        IndexViewPerformance record = new IndexViewPerformance();
        record.threshold = fieldSetFlags()[0] ? this.threshold : (java.lang.Long) defaultValue(fields()[0]);
        record.data = fieldSetFlags()[1] ? this.data : (java.util.List<sparqles.avro.analytics.IndexViewPerformanceData>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IndexViewPerformance>
    WRITER$ = (org.apache.avro.io.DatumWriter<IndexViewPerformance>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IndexViewPerformance>
    READER$ = (org.apache.avro.io.DatumReader<IndexViewPerformance>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.threshold);

    long size0 = this.data.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (sparqles.avro.analytics.IndexViewPerformanceData e0: this.data) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.threshold = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> a0 = this.data;
      if (a0 == null) {
        a0 = new SpecificData.Array<sparqles.avro.analytics.IndexViewPerformanceData>((int)size0, SCHEMA$.getField("data").schema());
        this.data = a0;
      } else a0.clear();
      SpecificData.Array<sparqles.avro.analytics.IndexViewPerformanceData> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<sparqles.avro.analytics.IndexViewPerformanceData>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          sparqles.avro.analytics.IndexViewPerformanceData e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new sparqles.avro.analytics.IndexViewPerformanceData();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.threshold = in.readLong();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<sparqles.avro.analytics.IndexViewPerformanceData> a0 = this.data;
          if (a0 == null) {
            a0 = new SpecificData.Array<sparqles.avro.analytics.IndexViewPerformanceData>((int)size0, SCHEMA$.getField("data").schema());
            this.data = a0;
          } else a0.clear();
          SpecificData.Array<sparqles.avro.analytics.IndexViewPerformanceData> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<sparqles.avro.analytics.IndexViewPerformanceData>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              sparqles.avro.analytics.IndexViewPerformanceData e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new sparqles.avro.analytics.IndexViewPerformanceData();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










