/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package sparqles.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Endpoint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5345063537835847863L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Endpoint\",\"namespace\":\"sparqles.avro\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"datasets\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Dataset\",\"fields\":[{\"name\":\"uri\",\"type\":\"string\"},{\"name\":\"label\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Endpoint> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Endpoint> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Endpoint> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Endpoint> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Endpoint> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Endpoint to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Endpoint from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Endpoint instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Endpoint fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence uri;
  private java.util.List<sparqles.avro.Dataset> datasets;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Endpoint() {}

  /**
   * All-args constructor.
   * @param uri The new value for uri
   * @param datasets The new value for datasets
   */
  public Endpoint(java.lang.CharSequence uri, java.util.List<sparqles.avro.Dataset> datasets) {
    this.uri = uri;
    this.datasets = datasets;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return uri;
    case 1: return datasets;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: uri = (java.lang.CharSequence)value$; break;
    case 1: datasets = (java.util.List<sparqles.avro.Dataset>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'uri' field.
   * @return The value of the 'uri' field.
   */
  public java.lang.CharSequence getUri() {
    return uri;
  }


  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.CharSequence value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'datasets' field.
   * @return The value of the 'datasets' field.
   */
  public java.util.List<sparqles.avro.Dataset> getDatasets() {
    return datasets;
  }


  /**
   * Sets the value of the 'datasets' field.
   * @param value the value to set.
   */
  public void setDatasets(java.util.List<sparqles.avro.Dataset> value) {
    this.datasets = value;
  }

  /**
   * Creates a new Endpoint RecordBuilder.
   * @return A new Endpoint RecordBuilder
   */
  public static sparqles.avro.Endpoint.Builder newBuilder() {
    return new sparqles.avro.Endpoint.Builder();
  }

  /**
   * Creates a new Endpoint RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Endpoint RecordBuilder
   */
  public static sparqles.avro.Endpoint.Builder newBuilder(sparqles.avro.Endpoint.Builder other) {
    if (other == null) {
      return new sparqles.avro.Endpoint.Builder();
    } else {
      return new sparqles.avro.Endpoint.Builder(other);
    }
  }

  /**
   * Creates a new Endpoint RecordBuilder by copying an existing Endpoint instance.
   * @param other The existing instance to copy.
   * @return A new Endpoint RecordBuilder
   */
  public static sparqles.avro.Endpoint.Builder newBuilder(sparqles.avro.Endpoint other) {
    if (other == null) {
      return new sparqles.avro.Endpoint.Builder();
    } else {
      return new sparqles.avro.Endpoint.Builder(other);
    }
  }

  /**
   * RecordBuilder for Endpoint instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Endpoint>
    implements org.apache.avro.data.RecordBuilder<Endpoint> {

    private java.lang.CharSequence uri;
    private java.util.List<sparqles.avro.Dataset> datasets;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(sparqles.avro.Endpoint.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.datasets)) {
        this.datasets = data().deepCopy(fields()[1].schema(), other.datasets);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Endpoint instance
     * @param other The existing instance to copy.
     */
    private Builder(sparqles.avro.Endpoint other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.uri)) {
        this.uri = data().deepCopy(fields()[0].schema(), other.uri);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.datasets)) {
        this.datasets = data().deepCopy(fields()[1].schema(), other.datasets);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'uri' field.
      * @return The value.
      */
    public java.lang.CharSequence getUri() {
      return uri;
    }


    /**
      * Sets the value of the 'uri' field.
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public sparqles.avro.Endpoint.Builder setUri(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.uri = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'uri' field.
      * @return This builder.
      */
    public sparqles.avro.Endpoint.Builder clearUri() {
      uri = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'datasets' field.
      * @return The value.
      */
    public java.util.List<sparqles.avro.Dataset> getDatasets() {
      return datasets;
    }


    /**
      * Sets the value of the 'datasets' field.
      * @param value The value of 'datasets'.
      * @return This builder.
      */
    public sparqles.avro.Endpoint.Builder setDatasets(java.util.List<sparqles.avro.Dataset> value) {
      validate(fields()[1], value);
      this.datasets = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'datasets' field has been set.
      * @return True if the 'datasets' field has been set, false otherwise.
      */
    public boolean hasDatasets() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'datasets' field.
      * @return This builder.
      */
    public sparqles.avro.Endpoint.Builder clearDatasets() {
      datasets = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Endpoint build() {
      try {
        Endpoint record = new Endpoint();
        record.uri = fieldSetFlags()[0] ? this.uri : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.datasets = fieldSetFlags()[1] ? this.datasets : (java.util.List<sparqles.avro.Dataset>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Endpoint>
    WRITER$ = (org.apache.avro.io.DatumWriter<Endpoint>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Endpoint>
    READER$ = (org.apache.avro.io.DatumReader<Endpoint>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.uri);

    long size0 = this.datasets.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (sparqles.avro.Dataset e0: this.datasets) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);

      long size0 = in.readArrayStart();
      java.util.List<sparqles.avro.Dataset> a0 = this.datasets;
      if (a0 == null) {
        a0 = new SpecificData.Array<sparqles.avro.Dataset>((int)size0, SCHEMA$.getField("datasets").schema());
        this.datasets = a0;
      } else a0.clear();
      SpecificData.Array<sparqles.avro.Dataset> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<sparqles.avro.Dataset>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          sparqles.avro.Dataset e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new sparqles.avro.Dataset();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.uri = in.readString(this.uri instanceof Utf8 ? (Utf8)this.uri : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<sparqles.avro.Dataset> a0 = this.datasets;
          if (a0 == null) {
            a0 = new SpecificData.Array<sparqles.avro.Dataset>((int)size0, SCHEMA$.getField("datasets").schema());
            this.datasets = a0;
          } else a0.clear();
          SpecificData.Array<sparqles.avro.Dataset> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<sparqles.avro.Dataset>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              sparqles.avro.Dataset e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new sparqles.avro.Dataset();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










